name: PHP Composer

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      # Mandatory : fetch the current repository
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: ctype, iconv
          tools: composer:2.6.5
          ini-values: post_max_size=56M, max_execution_time=30
          coverage: none
        env:
          update: true
          fail-fast: true
          APP_ENV: "test"

      - name: Fix not existed .env file
        working-directory: app
        run: pwd && cp .env.test .env && ls -lna
      
      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}

      - name: Validate composer.json and composer.lock
        working-directory: app
        run: composer validate --strict

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ./app
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: ${{ runner.os }}-composer-
    
      - name: Install dependencies
        working-directory: app
        run: composer install --prefer-dist
  
      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
  
      - name: Run test suite
        working-directory: app
        run: composer run-script test
